### ISSUE TITLE
Instruction unclear, password file not found, house on fire

### ISSUE THREAD

**Issue by derNiklaas** [TrojanerHD/Ichi#4]
Yes. please include a default password file. thanks.
`
[Error: ENOENT: no such file or directory, open 'C:\Users\Niklas\Desktop\Ichi\Ich
i-master\room_password.txt'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\Niklas\\Desktop\\Ichi\\Ichi-master\\room_password.txt'
}
`

**Comment by TrojanerHD** [comment]
Fixed in https://github.com/TrojanerHD/Ichi/commit/3255901750be6a7f13c351af7e278f235f908d97 and https://github.com/TrojanerHD/Ichi/commit/1053d4e378ad7f184c7ba36af06a4a806263681d
