### ISSUE TITLE
Instruction unclear, Password must not equals password in passwordfile, Tsunami hit town

### ISSUE THREAD

**Issue by justliliandev** [TrojanerHD/Ichi#5]

**Comment by TrojanerHD** [comment]
Fixed in https://github.com/TrojanerHD/Ichi/commit/7945fb701cec3bce8fbbcbd894253a9a03928508 and https://github.com/TrojanerHD/Ichi/commit/ec2d11142cf13837323f8e99a2e11599b0c7e4e3
